const people=[
{id:'dad',name:'Father',letter:'F',color:'#4c7982',time:'06:00',zone:'WASHING AREA',world:'The Wishing Well',mark:'≈',object:'Kettle',objectIcon:'♨',intro:'Before the house wakes, something has already begun.',story:'Before anyone woke, Father prepared what the family would need and sometimes helped Grandfather with his routine. His care lived in things completed before anyone was watching.',clues:[['Sound','A low tremor gathers into a soft, restless murmur.'],['Touch','A smooth surface holds a warmth that is slowly fading.'],['Sight','A pale ring surrounds a faint brown shadow.'],['Scent','Warm air carries a distant trace of damp leaves and earth.'],['Sight','One curved edge has been handled until its finish softened.']]},
{id:'mom',name:'Mother',letter:'M',color:'#a94d3c',time:'12:00',zone:'COOKING AREA',world:'The Living Volcano',mark:'▲',object:'Spatula',objectIcon:'◒',intro:'She remembers what everyone likes, even when nobody asks.',story:'Mother called every meal ordinary, yet remembered exactly what everyone liked. A faded thread tied there by the child years ago remained untouched.',clues:[['Sound','A bright repeating note touches another surface, pauses, and begins again.'],['Touch','One side feels polished by a familiar grip.'],['Sight','Fine silver lines end beside a faded red thread.'],['Taste','Something familiar begins savoury and leaves a little sweetness.'],['Scent','A lively warmth rises briefly, then settles into the room.']]},
{id:'grandpa',name:'Grandfather',letter:'G',color:'#637c58',time:'16:00',zone:'STORAGE CABINET',world:'The Forest',mark:'♧',object:'Herbal medicine pot',objectIcon:'♧',intro:'After every bitter afternoon, someone saved something sweet.',story:'After Grandfather completed his old routine, someone always handed him a sweet. Long after it ended, sweets remained in the kitchen drawer.',clues:[['Scent','A dense, earthy bitterness settles into every corner.'],['Sound','A light piece lifts, falls, and taps an uneven rhythm.'],['Sight','A rim darkened by time carries one repaired line.'],['Touch','The coarse surface keeps its warmth longer than expected.'],['Taste','A deep bitterness arrives; memory insists sweetness follows.']]},
{id:'child',name:'Child',letter:'C',color:'#d0a532',time:'22:00',zone:'PREP AREA',world:'The Machine Works',mark:'⚙',object:'Coffee maker',objectIcon:'♜',intro:'Growing up tastes bitter, but home still leaves something sweet.',story:'Now grown, the child often returned late and worked alone. Mother never understood the new routine, but a plate of cut fruit always appeared nearby.',clues:[['Sound','A deep mechanical hum breaks the late quiet, then stops.'],['Scent','A dark toasted aroma hangs with a nut-like warmth.'],['Sight','A half-written work note rests beside a small round stain.'],['Touch','A nearby vessel is warm; one small control has lost its shine.'],['Taste','The first impression is dry and bitter, then softens.']]}
];
const distractors=[['Teapot','♨'],['Rice cooker','◉'],['Soup ladle','◒'],['Thermos','▥'],['Mortar and pestle','♢'],['Toaster','▦'],['Kitchen timer','◷'],['Ceramic bowl','◡']];
const icons={Sound:'⌁',Touch:'◇',Sight:'◉',Scent:'≈',Taste:'●'};
let state={mode:'single',selected:[],active:null,returned:[]};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),person=id=>people.find(p=>p.id===id);
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function modal(id,on=true){$('#'+id).classList.toggle('open',on)}
function notify(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function reset(){state={mode:'single',selected:[],active:null,returned:[]};people.forEach(p=>{p.found=[];p.identified=false});$$('.modal').forEach(x=>x.classList.remove('open'));show('welcome')}
function chooseMode(mode){state.mode=mode;state.selected=[];$('#roleTitle').textContent=mode==='single'?'Whose story will you follow?':'Who is playing today?';$('#roleHelp').textContent=mode==='single'?'Select one family member to enter their world.':'Select two to four family members. Turns follow the kitchen clock.';renderRoles();show('roles')}
function renderRoles(){
 $('#roleGrid').innerHTML=people.map(p=>`<button class="rolecard ${state.selected.includes(p.id)?'selected':''}" data-p="${p.id}" style="--role:${p.color}"><div class="portrait">${p.letter}</div><div class="roleinfo"><small>${p.time} · ${p.world.toUpperCase()}</small><h3>${p.name}</h3><p>${p.intro}</p></div></button>`).join('');
 $$('.rolecard').forEach(b=>b.onclick=()=>toggleRole(b.dataset.p));const n=state.selected.length,min=state.mode==='single'?1:2;$('#selectionText').textContent=state.mode==='single'?(n?'One character selected':'Choose one character'):`${n} selected · choose 2–4`;$('#enter').disabled=n<min;
}
function toggleRole(id){if(state.mode==='single')state.selected=[id];else if(state.selected.includes(id))state.selected=state.selected.filter(x=>x!==id);else if(state.selected.length<4)state.selected.push(id);renderRoles()}
function enterWorld(){state.selected.sort((a,b)=>people.indexOf(person(a))-people.indexOf(person(b)));state.active=state.selected[0];renderWorld();show('world')}
function renderWorld(){
 const p=person(state.active),done=state.returned.length;document.documentElement.style.setProperty('--role',p.color);
 $$('.realm').forEach(r=>{const id=r.dataset.role;r.classList.toggle('available',id===state.active&&!state.returned.includes(id));r.classList.toggle('complete',state.returned.includes(id))});
 $('#journeys').innerHTML=state.selected.map(id=>{const x=person(id);return `<div class="journey ${id===state.active?'active':''} ${state.returned.includes(id)?'done':''}"><b>${x.time} · ${x.name}</b><span>${state.returned.includes(id)?'Object returned':id===state.active?'Journey illuminated':'Waiting in the kitchen'}</span></div>`}).join('');
 $('#current').className='current';$('#current').style.setProperty('--role',p.color);$('#current').innerHTML=`<i>${p.letter}</i><h3>${p.name}</h3><p>${p.time} · ${p.world}</p><p>${p.intro}</p>`;$('#progressText').textContent=`${done} / ${state.selected.length}`;$('#bar').style.width=`${done/state.selected.length*100}%`;$('#returned').textContent=state.returned.map(id=>person(id).objectIcon).join(' ');
}
function openScene(id){if(id!==state.active||state.returned.includes(id)){notify(state.returned.includes(id)?'This object is already home.':'This memory is dim. Follow the illuminated world.');return}const p=person(id);show('scene');$('#sceneName').textContent=p.world;$('#sceneRole').textContent=`${p.name} · ${p.time}`;$('#memoryName').textContent=`${p.name}'s memory`;$('#landmark').textContent=p.mark;$('#token').textContent=p.letter;$('#sceneArt').style.cssText=`--light:${p.color};--dark:#142c27;--role:${p.color}`;renderNodes()}
function renderNodes(){const p=person(state.active);$('#nodes').innerHTML=p.clues.map((c,i)=>`<button class="node ${p.found.includes(i)?'found':''}" data-i="${i}">${icons[c[0]]}</button>`).join('');$$('.node').forEach(n=>n.onclick=()=>findClue(+n.dataset.i));$('#clueList').innerHTML=p.clues.map((c,i)=>p.found.includes(i)?`<div class="miniclue"><b>${icons[c[0]]} ${c[0]}</b>${c[1]}</div>`:`<div class="miniclue empty">○ Undiscovered trace</div>`).join('');$('#guess').disabled=p.found.length<3}
function findClue(i){const p=person(state.active);if(p.found.includes(i))return notify('You have already gathered this trace.');p.found.push(i);const c=p.clues[i];$('#sense').textContent=c[0].toUpperCase();$('#senseIcon').textContent=icons[c[0]];$('#clueText').textContent=c[1];renderNodes();modal('clueModal')}
function guess(){const p=person(state.active),pool=[[p.object,p.objectIcon],...distractors.sort(()=>Math.random()-.5).slice(0,7)].sort(()=>Math.random()-.5);$('#options').innerHTML=pool.map(x=>`<button class="object" data-o="${x[0]}"><span>${x[1]}</span>${x[0]}</button>`).join('');$$('.object').forEach(b=>b.onclick=()=>checkGuess(b.dataset.o));modal('guessModal')}
function checkGuess(o){const p=person(state.active);modal('guessModal',false);if(o!==p.object)return notify('That object cannot explain every trace. Look again.');p.identified=true;$('#objectIcon').textContent=p.objectIcon;$('#objectName').textContent=`${p.name}'s ${p.object.toLowerCase()}`;$('#story').textContent=p.story;$('#fromWorld').textContent=p.world;modal('returnModal')}
function returnObject(){const id=state.active;state.returned.push(id);modal('returnModal',false);if(state.returned.length===state.selected.length)return finish();const remaining=state.selected.filter(x=>!state.returned.includes(x));state.active=remaining[0];renderWorld();show('world');notify(`${person(id).name}'s object is back where it belongs. ${person(state.active).name}'s world now glows.`)}
function finish(){show('world');renderWorld();$('#finalStories').innerHTML=state.selected.map(id=>{const p=person(id);return `<div><b>${p.name} · ${p.object}</b><p>${p.story}</p></div>`}).join('');setTimeout(()=>modal('ending'),500)}
function openJournal(){const selected=state.selected.length?state.selected:people.map(p=>p.id);$('#tabs').innerHTML=selected.map((id,i)=>`<button class="${i?'':'active'}" data-t="${id}">${person(id).name}</button>`).join('');$$('#tabs button').forEach(b=>b.onclick=()=>{$$('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderJournal(b.dataset.t)});renderJournal(selected[0]);modal('journalModal')}
function renderJournal(id){const p=person(id);$('#journalBody').innerHTML=p.found.length?p.found.map(i=>`<div class="entry"><b>${icons[p.clues[i][0]]} ${p.clues[i][0]}</b><span>${p.clues[i][1]}</span></div>`).join(''):'<p>No traces have surfaced yet.</p>'}
$('#begin').onclick=()=>show('mode');$$('[data-mode]').forEach(b=>b.onclick=()=>chooseMode(b.dataset.mode));$$('[data-show]').forEach(b=>b.onclick=()=>show(b.dataset.show));$$('[data-home]').forEach(b=>b.onclick=reset);$('#enter').onclick=enterWorld;$$('.realm').forEach(b=>b.onclick=()=>openScene(b.dataset.role));$('#mapBack').onclick=()=>{renderWorld();show('world')};$('#guess').onclick=guess;$('#returnObject').onclick=returnObject;$('#journal').onclick=openJournal;$('#restart').onclick=reset;$('#sound').onclick=()=>notify('Ambient sound is ready for your future audio files.');$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));people.forEach(p=>p.found=[]);
